"""add fk fields to statement

Revision ID: 0f14c6ad4556
Revises: 16c7ea815f38
Create Date: 2025-08-04 10:23:30.259448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f14c6ad4556'
down_revision: Union[str, Sequence[str], None] = '16c7ea815f38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statements', sa.Column('firm_id', sa.Integer(), nullable=True))
    op.add_column('statements', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('statements', sa.Column('up_company_id', sa.Integer(), nullable=True))
    op.add_column('statements', sa.Column('group_id', sa.Integer(), nullable=True))
    op.add_column('statements', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_statements_category_id'), 'statements', ['category_id'], unique=False)
    op.create_index(op.f('ix_statements_company_id'), 'statements', ['company_id'], unique=False)
    op.create_index(op.f('ix_statements_firm_id'), 'statements', ['firm_id'], unique=False)
    op.create_index(op.f('ix_statements_group_id'), 'statements', ['group_id'], unique=False)
    op.create_index(op.f('ix_statements_up_company_id'), 'statements', ['up_company_id'], unique=False)
    op.create_foreign_key(None, 'statements', 'up_company', ['up_company_id'], ['id'])
    op.create_foreign_key(None, 'statements', 'company', ['company_id'], ['id'])
    op.create_foreign_key(None, 'statements', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'statements', 'firms', ['firm_id'], ['id'])
    op.create_foreign_key(None, 'statements', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'statements', type_='foreignkey')
    op.drop_constraint(None, 'statements', type_='foreignkey')
    op.drop_constraint(None, 'statements', type_='foreignkey')
    op.drop_constraint(None, 'statements', type_='foreignkey')
    op.drop_constraint(None, 'statements', type_='foreignkey')
    op.drop_index(op.f('ix_statements_up_company_id'), table_name='statements')
    op.drop_index(op.f('ix_statements_group_id'), table_name='statements')
    op.drop_index(op.f('ix_statements_firm_id'), table_name='statements')
    op.drop_index(op.f('ix_statements_company_id'), table_name='statements')
    op.drop_index(op.f('ix_statements_category_id'), table_name='statements')
    op.drop_column('statements', 'category_id')
    op.drop_column('statements', 'group_id')
    op.drop_column('statements', 'up_company_id')
    op.drop_column('statements', 'company_id')
    op.drop_column('statements', 'firm_id')
    # ### end Alembic commands ###
