"""add fk fields to statement

Revision ID: 7b68b8597a76
Revises: 28deb0987194
Create Date: 2025-08-04 15:46:30.557823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b68b8597a76'
down_revision: Union[str, Sequence[str], None] = '28deb0987194'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statements', sa.Column('payer_raw', sa.String(), nullable=True, comment='Плательщик (оригинал из выписки)'))
    op.add_column('statements', sa.Column('receiver_raw', sa.String(), nullable=True, comment='Получатель (оригинал из выписки)'))
    op.alter_column('statements', 'payer_inn',
               existing_type=sa.VARCHAR(),
               comment='ИНН плательщика из выписки',
               existing_nullable=True)
    op.alter_column('statements', 'receiver_inn',
               existing_type=sa.VARCHAR(),
               comment='ИНН получателя из выписки',
               existing_nullable=True)
    op.drop_column('statements', 'payer')
    op.drop_column('statements', 'receiver')
    op.drop_column('statements', 'category')
    op.drop_column('statements', 'group')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statements', sa.Column('group', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('statements', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('statements', sa.Column('receiver', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('statements', sa.Column('payer', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('statements', 'receiver_inn',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='ИНН получателя из выписки',
               existing_nullable=True)
    op.alter_column('statements', 'payer_inn',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='ИНН плательщика из выписки',
               existing_nullable=True)
    op.drop_column('statements', 'receiver_raw')
    op.drop_column('statements', 'payer_raw')
    # ### end Alembic commands ###
