"""ф

Revision ID: 8cbd56814dc3
Revises: b8d9eebe368d
Create Date: 2025-08-14 13:16:50.489469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cbd56814dc3'
down_revision: Union[str, Sequence[str], None] = 'b8d9eebe368d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('editbank', sa.Column('za_kogo_platili_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_editbank_za_kogo_platili_id'), 'editbank', ['za_kogo_platili_id'], unique=False)
    op.create_foreign_key(None, 'editbank', 'up_company', ['za_kogo_platili_id'], ['id'])
    op.add_column('statements', sa.Column('za_kogo_platili_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'statements', 'up_company', ['za_kogo_platili_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'statements', type_='foreignkey')
    op.drop_column('statements', 'za_kogo_platili_id')
    op.drop_constraint(None, 'editbank', type_='foreignkey')
    op.drop_index(op.f('ix_editbank_za_kogo_platili_id'), table_name='editbank')
    op.drop_column('editbank', 'za_kogo_platili_id')
    # ### end Alembic commands ###
