"""add fk fields to statement

Revision ID: de77e51c22dd
Revises: fe4f5906eea1
Create Date: 2025-08-04 15:18:37.922788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de77e51c22dd'
down_revision: Union[str, Sequence[str], None] = 'fe4f5906eea1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statements', sa.Column('payer_company_id', sa.Integer(), nullable=True, comment='Плательщик (Company)'))
    op.add_column('statements', sa.Column('payer_firm_id', sa.Integer(), nullable=True, comment='Плательщик (Firm)'))
    op.add_column('statements', sa.Column('receiver_company_id', sa.Integer(), nullable=True, comment='Получатель (Company)'))
    op.add_column('statements', sa.Column('receiver_firm_id', sa.Integer(), nullable=True, comment='Получатель (Firm)'))
    op.drop_constraint(op.f('statements_payer_id_fkey'), 'statements', type_='foreignkey')
    op.drop_constraint(op.f('statements_receiver_id_fkey'), 'statements', type_='foreignkey')
    op.create_foreign_key(None, 'statements', 'company', ['receiver_company_id'], ['id'])
    op.create_foreign_key(None, 'statements', 'company', ['payer_company_id'], ['id'])
    op.create_foreign_key(None, 'statements', 'firms', ['payer_firm_id'], ['id'])
    op.create_foreign_key(None, 'statements', 'firms', ['receiver_firm_id'], ['id'])
    op.drop_column('statements', 'receiver_id')
    op.drop_column('statements', 'payer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statements', sa.Column('payer_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='Плательщик'))
    op.add_column('statements', sa.Column('receiver_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='Получатель'))
    op.drop_constraint(None, 'statements', type_='foreignkey')
    op.drop_constraint(None, 'statements', type_='foreignkey')
    op.drop_constraint(None, 'statements', type_='foreignkey')
    op.drop_constraint(None, 'statements', type_='foreignkey')
    op.create_foreign_key(op.f('statements_receiver_id_fkey'), 'statements', 'company', ['receiver_id'], ['id'])
    op.create_foreign_key(op.f('statements_payer_id_fkey'), 'statements', 'company', ['payer_id'], ['id'])
    op.drop_column('statements', 'receiver_firm_id')
    op.drop_column('statements', 'receiver_company_id')
    op.drop_column('statements', 'payer_firm_id')
    op.drop_column('statements', 'payer_company_id')
    # ### end Alembic commands ###
