"""add fk fields to statement

Revision ID: fe4f5906eea1
Revises: 0f14c6ad4556
Create Date: 2025-08-04 14:38:22.341653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe4f5906eea1'
down_revision: Union[str, Sequence[str], None] = '0f14c6ad4556'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statements', sa.Column('payer_id', sa.Integer(), nullable=True, comment='Плательщик'))
    op.add_column('statements', sa.Column('receiver_id', sa.Integer(), nullable=True, comment='Получатель'))
    op.drop_index(op.f('ix_statements_company_id'), table_name='statements')
    op.drop_index(op.f('ix_statements_firm_id'), table_name='statements')
    op.drop_constraint(op.f('statements_firm_id_fkey'), 'statements', type_='foreignkey')
    op.drop_constraint(op.f('statements_company_id_fkey'), 'statements', type_='foreignkey')
    op.create_foreign_key(None, 'statements', 'company', ['receiver_id'], ['id'])
    op.create_foreign_key(None, 'statements', 'company', ['payer_id'], ['id'])
    op.drop_column('statements', 'company_id')
    op.drop_column('statements', 'firm_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statements', sa.Column('firm_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('statements', sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'statements', type_='foreignkey')
    op.drop_constraint(None, 'statements', type_='foreignkey')
    op.create_foreign_key(op.f('statements_company_id_fkey'), 'statements', 'company', ['company_id'], ['id'])
    op.create_foreign_key(op.f('statements_firm_id_fkey'), 'statements', 'firms', ['firm_id'], ['id'])
    op.create_index(op.f('ix_statements_firm_id'), 'statements', ['firm_id'], unique=False)
    op.create_index(op.f('ix_statements_company_id'), 'statements', ['company_id'], unique=False)
    op.drop_column('statements', 'receiver_id')
    op.drop_column('statements', 'payer_id')
    # ### end Alembic commands ###
